// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using River.Infrastructure.DataAccessLayer;

#nullable disable

namespace River.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.IgnoredDirectoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                     .IsUnique()
                     .HasDatabaseName("IX_ignored_directory_path");

                    b.ToTable("ignored_directory", null, t =>
                        {
                            t.HasComment("Represents an ignorable directory. All children files are considered ignorable.");
                        });
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.IgnoredFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                     .IsUnique()
                     .HasDatabaseName("IX_ignored_file_path");

                    b.ToTable("ignored_file", null, t =>
                        {
                            t.HasComment("Represents an ignorable file.");
                        });
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.TrackedDirectoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                     .IsUnique()
                     .HasDatabaseName("IX_tracked_directory_path");

                    b.ToTable("tracked_directory", null, t =>
                        {
                            t.HasComment("Represents a trackable directory. Changes to the directory, or any of its children files, are also trackable.");
                        });
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.TrackedFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("DirectoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("directory_id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.HasIndex("Path")
                     .IsUnique()
                     .HasDatabaseName("IX_tracked_file_path");

                    b.ToTable("tracked_file", null, t =>
                        {
                            t.HasComment("Represents a trackable file with a parent directory reference. Changes to the parent are also trackable.");
                        });
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.TrackedSoloFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean")
                        .HasColumnName("inactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                     .IsUnique()
                     .HasDatabaseName("IX_tracked_solo_file_path");

                    b.ToTable("tracked_solo_file", null, t =>
                        {
                            t.HasComment("Represents a trackable file with no parent directory reference.");
                        });
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.TrackedFileEntity", b =>
                {
                    b.HasOne("River.Infrastructure.DataAccessLayer.Entities.TrackedDirectoryEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("River.Infrastructure.DataAccessLayer.Entities.TrackedDirectoryEntity", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
